package Game;


import java.awt.event.ActionEvent;
import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;


public class Answer_What extends javax.swing.JFrame  implements MyUtil{

    private String[] args;

    /**
     * Creates new form Answer_What
     */
    public Answer_What() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        What = new javax.swing.JLabel();
        One = new javax.swing.JButton();
        Two = new javax.swing.JButton();
        Three = new javax.swing.JButton();
        Four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        What.setFont(new java.awt.Font("Angsana New", 1, 48)); // NOI18N
        What.setForeground(new java.awt.Color(255, 255, 255));
        What.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        What.setText("เหตุจูงใจ ?");
        jPanel1.add(What);
        What.setBounds(530, 90, 240, 80);

        One.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        One.setText("ต้องการมรดก");
        One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneActionPerformed(evt);
            }
        });
        jPanel1.add(One);
        One.setBounds(470, 220, 350, 50);

        Two.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        Two.setText("พลั้งมือฆ่า");
        Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoActionPerformed(evt);
            }
        });
        jPanel1.add(Two);
        Two.setBounds(470, 310, 350, 50);

        Three.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        Three.setText("ฆ่าผิดตัว");
        Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeActionPerformed(evt);
            }
        });
        jPanel1.add(Three);
        Three.setBounds(470, 400, 350, 50);

        Four.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        Four.setText("วางแผนขโมยของในบ้าน");
        Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourActionPerformed(evt);
            }
        });
        jPanel1.add(Four);
        Four.setBounds(470, 490, 350, 50);

        five.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        five.setText("ชู้สาว");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        jPanel1.add(five);
        five.setBounds(470, 580, 350, 50);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/AnsBG.png"))); // NOI18N
        jPanel1.add(BG);
        BG.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    static void Playsound(File Sound){
        try {
         // Open an audio input stream.
         Clip clip = AudioSystem.getClip();
         clip.open(AudioSystem.getAudioInputStream(Sound));
         clip.start();
         
         Thread.sleep(clip.getMicrosecondLength()/1000);
         
        }catch(Exception e){
        }
    }
    
    private void OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneActionPerformed
            File backk = new File("buttonMenu.wav");
            Playsound(backk);
            Text2[3] = One.getText();
         if("ลูกชาย".equals(Text2[0]) && "มีด".equals(Text2[1])&& "ห้องน้ำ".equals(Text2[2])&& "ต้องการมรดก".equals(Text2[3])){
            ;
             Win next = new Win();
            next.setVisible(true);
            setVisible(false);
        }else{
            Loss next = new Loss();
            next.setVisible(true);
            setVisible(false);
        } 
    }//GEN-LAST:event_OneActionPerformed

    private void TwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoActionPerformed
       File backk = new File("buttonMenu.wav");
       Playsound(backk);
       Text2[3] = Two.getText();
       if("ลูกชาย".equals(Text2[0]) && "มีด".equals(Text2[1])&& "ห้องน้ำ".equals(Text2[2])&& "ต้องการมรดก".equals(Text2[3])){
            
           Win next = new Win();
            next.setVisible(true);
            setVisible(false);
        }else{
            Loss next = new Loss();
            next.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_TwoActionPerformed

    private void ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeActionPerformed
       File backk = new File("buttonMenu.wav");
            Playsound(backk);
        Text2[3] = Three.getText();
       if("ลูกชาย".equals(Text2[0]) && "มีด".equals(Text2[1])&& "ห้องน้ำ".equals(Text2[2])&& "ต้องการมรดก".equals(Text2[3])){
            Win next = new Win();
            next.setVisible(true);
            setVisible(false);
        }else{
            Loss next = new Loss();
            next.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_ThreeActionPerformed

    private void FourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourActionPerformed
        File backk = new File("buttonMenu.wav");
            Playsound(backk);
        Text2[3] = Four.getText();
        if("ลูกชาย".equals(Text2[0]) && "มีด".equals(Text2[1])&& "ห้องน้ำ".equals(Text2[2])&& "ต้องการมรดก".equals(Text2[3])){
            Win next = new Win();
            next.setVisible(true);
            setVisible(false);
        }else{
            Loss next = new Loss();
            next.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_FourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        File backk = new File("buttonMenu.wav");
        Playsound(backk);
        Text2[3] = five.getText();
        if("ลูกชาย".equals(Text2[0]) && "มีด".equals(Text2[1])&& "ห้องน้ำ".equals(Text2[2])&& "ต้องการมรดก".equals(Text2[3])){
            Win next = new Win();
            next.setVisible(true);
            setVisible(false);
        }else{
            Loss next = new Loss();
            next.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_fiveActionPerformed

    
     /* @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Answer_What.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Answer_What.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Answer_What.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Answer_What.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Answer_What().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton Four;
    private javax.swing.JButton One;
    private javax.swing.JButton Three;
    private javax.swing.JButton Two;
    private javax.swing.JLabel What;
    private javax.swing.JButton five;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
