package Game;


import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Answer_Where extends javax.swing.JFrame implements MyUtil{

    /**
     * Creates new form Answer_Where
     */
    public Answer_Where() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chiken = new javax.swing.JButton();
        BathRoom = new javax.swing.JButton();
        FatherRoom = new javax.swing.JButton();
        SisterRoom = new javax.swing.JButton();
        Library = new javax.swing.JButton();
        Where = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        chiken.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        chiken.setText("ห้องครัว");
        chiken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chikenActionPerformed(evt);
            }
        });
        jPanel1.add(chiken);
        chiken.setBounds(470, 590, 350, 50);

        BathRoom.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        BathRoom.setText("ห้องน้ำ");
        BathRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BathRoomActionPerformed(evt);
            }
        });
        jPanel1.add(BathRoom);
        BathRoom.setBounds(470, 320, 350, 50);

        FatherRoom.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        FatherRoom.setText("ห้องพ่อ");
        FatherRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherRoomActionPerformed(evt);
            }
        });
        jPanel1.add(FatherRoom);
        FatherRoom.setBounds(470, 230, 350, 50);

        SisterRoom.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        SisterRoom.setText("ห้องลูกสาว");
        SisterRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SisterRoomActionPerformed(evt);
            }
        });
        jPanel1.add(SisterRoom);
        SisterRoom.setBounds(470, 410, 350, 50);

        Library.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        Library.setText("ห้องสมุด");
        Library.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryActionPerformed(evt);
            }
        });
        jPanel1.add(Library);
        Library.setBounds(470, 500, 350, 50);

        Where.setFont(new java.awt.Font("Angsana New", 1, 48)); // NOI18N
        Where.setForeground(new java.awt.Color(255, 255, 255));
        Where.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Where.setText("สถานที่ที่เกิดเหตุฆาตกรรม?");
        jPanel1.add(Where);
        Where.setBounds(320, 90, 650, 80);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/AnsBG.png"))); // NOI18N
        jPanel1.add(BG);
        BG.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    static void Playsound(File Sound){
        try {
         // Open an audio input stream.
         Clip clip = AudioSystem.getClip();
         clip.open(AudioSystem.getAudioInputStream(Sound));
         clip.start();
         
         Thread.sleep(clip.getMicrosecondLength()/1000);
         
        }catch(Exception e){
        }
    }
    
    private void FatherRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherRoomActionPerformed
            File backk = new File("buttonMenu.wav");
            Playsound(backk);
            Text2[2] = FatherRoom.getText();
            Answer_What nextt = new Answer_What();
            nextt.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_FatherRoomActionPerformed

    private void BathRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BathRoomActionPerformed
            File backk = new File("buttonMenu.wav");
            Playsound(backk);
            Text2[2] =BathRoom.getText();
            Answer_What nextt = new Answer_What();
            nextt.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_BathRoomActionPerformed

    private void SisterRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SisterRoomActionPerformed
            File backk = new File("buttonMenu.wav");
            Playsound(backk);
            Text2[2] =SisterRoom.getText();
            Answer_What nextt = new Answer_What();
            nextt.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_SisterRoomActionPerformed

    private void LibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryActionPerformed
            File backk = new File("buttonMenu.wav");
            Playsound(backk);
            Text2[2] =Library.getText();
            Answer_What nextt = new Answer_What();
            nextt.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_LibraryActionPerformed

    private void chikenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chikenActionPerformed
            File backk = new File("buttonMenu.wav");
            Playsound(backk);
            Text2[2] =chiken.getText();
            Answer_What nextt = new Answer_What();
            nextt.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_chikenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Answer_Where.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Answer_Where.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Answer_Where.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Answer_Where.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Answer_Where().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton BathRoom;
    private javax.swing.JButton FatherRoom;
    private javax.swing.JButton Library;
    private javax.swing.JButton SisterRoom;
    private javax.swing.JLabel Where;
    private javax.swing.JButton chiken;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
